name: Copy Secret to New Repo

on:
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy SEALOS_KUBECONFIG
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          KUBECONFIG: ${{ secrets.SEALOS_KUBECONFIG }}
        run: |
          echo "$KUBECONFIG" | gh secret set SEALOS_KUBECONFIG --repo ljx0722/video-3d-reconstruction
